image: jelaniwoods/appdev2023-vanilla-railsx-global

tasks:
  - before: |
      bin/setup
      .vscode/manage_extensions
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 9500-9999
    onOpen: ignore
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - jnbt.vscode-rufo
    - aliariff.vscode-erb-beautify
