databases:
  - name: appdev_template
    databaseName: appdev_template
    user: appdev_template
    plan: free

services:
  - type: web
    name: appdev_template
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: appdev_template
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
      
