databases:
  - name: vanilla-railsx
    databaseName: vanilla-railsx
    user: vanilla-railsx

services:
  - type: web
    name: vanilla-railsx
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vanilla-railsx
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
