#!/usr/bin/env ruby

unwanted_extensions = [
  "k--kato.intellij-idea-keybindings",
  "kaiwood.endwise",
  "castwide.solargraph",
]

wanted_extensions = [
  "vscode-rufo-0.0.6.vsix"
]

unwanted_extensions.each do |extension|
  results = `code --uninstall-extension #{extension}`
  if results.include?("successfully uninstalled")
    status = "successful"
  elsif results.include?("is not installed")
    status = "(wasn't installed)"
  else
    status = "failed"
  end
  puts "Uninstalled #{extension} - #{status}"
end

wanted_extensions.each do |extension|
  results = `code --install-extension #{extension}`
  if results.include?("successfully installed")
    status = "successful"
  elsif results.include?("is not installed")
    status = "failed"
  else
    status = "(wasn't installed)"
  end
  puts "Installed #{extension} - #{status}"
end
